version: '2'

services:
    mqtt:
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
            - "9001:9001"
        #volumes:
         #   - $HOME/mqtt/config:/mosquitto/config
         #   - $HOME/mqtt/data:/mosquitto/data
         #   - $HOME/mqtt/log:/mosquitto/log
    
    customer:
        image: ramazanfirin/customerraspberry:latest
        ports:
            - "8080:8080"
        depends_on:
            - mqtt
        #volumes:
         #   - $HOME/mqtt/config:/mosquitto/config
         #   - $HOME/mqtt/data:/mosquitto/data
         #   - $HOME/mqtt/log:/mosquitto/log